### PR TITLE
Add SSHProxy Server proposal

### PR DESCRIPTION
**Pull request by MohammadBilalArif**

### CODE REVIEW

**Comment by kung-foo** [comment]
Right now we have three `Server`s, two loggers and a proxy. I think that as we need to add additional handlers, we should think about changing the architecture to maybe allow the user to register a handler based on a tag. For example, if we had a rule like:

```yaml
rules:
  - match: tcp dst port 22
    type: conn_handler
    target: mtim_ssh
```

Somewhere else (i.e `main.go`), you could register a handler:

```go
p := freiki.New()
p.RegisterConnHandler("mitm_ssh", func(conn net.Conn, md *Metadata) error {return nil})
```

And then, inside of freki conn handler, I would pass the connection to your code:

```go
func (p *TCPConnHandler) handleConnection(conn net.Conn) {
    md := h.processor.Connections.GetByFlow(...)
    
    go func() {
        defer func() {
            // recover panic
            conn.Close()
        }()
        p.processor.handlers[md.target](conn, md)
    }()
}
```

Thoughts?

**Comment by MohammadBilalArif** [comment]
Sounds great :) Freki will become more generic.

**Comment by kung-foo** [comment]
Closing for now. Will use your code to test a new conn handler.

**Comment by kung-foo** [comment]
@MohammadBilalArif v1.1.0 is ready to go. Let's see that ssh sniffer in action!

**Comment by MohammadBilalArif** [comment]
I just passed conn to SSH sniffer. working great :)
Thanks man!

**Pull request closed without merging**
