### PR TITLE
Go modules and misc

### PR DESCRIPTION
**Pull request by glaslos**
- Switched from glide to go modules
- Removed vendor directory
- Fixed types in netfilter package
- Switched from Travis-CI to GitHub Actions
- Dockerfile cleanups
- Some linter errors

### CODE REVIEW

**Comment by kung-foo** [comment]
image

Does the `.github` folder have a leading space?

**Comment by glaslos** [comment]
I guess `port.party:666` is gone 😢

**Comment by glaslos** [comment]
Yeah, test broke, will try tomorrow with some http bin

**Comment by kung-foo** [comment]
`port.party` has always had stability issues. Maybe with a fresh freki build it will all work :)

**Comment by glaslos** [comment]
There is something up with the connection management 🤔 I'm working on a Freki successor.

**Comment by kung-foo** [comment]
yeah, the half-assed conntracking was a weak point.

**Pull request merged**
